export default [
	{
		rules: {
			'arrow-body-style': ['error', 'never'],
			'comma-dangle': [2, 'always-multiline'],
			'curly': 'error',
			'dot-notation': 'error',
			'eol-last': ['error', 'never'],
			'eqeqeq': 'error',
			'for-direction': 'error',
			'func-names': ['error', 'always'],
			'indent': ['error', 'tab'],
			'max-len': ['error', { 'code': 128, 'ignoreComments': true }],
			'no-extra-semi': 'error',
			'no-multi-spaces': 'error',
			'no-prototype-builtins': 'off',
			'no-trailing-spaces': 'error',
			'no-unreachable': 'error',
			'no-unused-expressions': 'error',
			'no-unused-vars': ['error', { 'args': 'after-used' }],
			'no-var': 'error',
			'one-var': ['error', 'never'],
			'prefer-arrow-callback': 'error',
			'quotes': ['error', 'single'],
			'semi': 'error',
			'unicode-bom': ['error', 'never'],
		},
	},
];